Implemented number of holders for a token
CoreumFoundation/callisto pull request #40
Opened 2023-11-22 12:57 UTC by miladz68

This PR, collects and expose info, regarding how many accounts are holding a specific token.

2023-11-22 16:27 UTC, ysv requested changes
> Reviewed 11 of 11 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: all files reviewed, 9 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`database/bank.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjroK194Eg-dkyQbOPr:-NjroK194Eg-dkyQbOPs:bnawsx2) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/bank.go#L31)):*
> ```Go
> 
> // SaveSupply allows to save for the given height the given total amount of coins
> func (db *Db) SaveAccountDenomBalance(account string, coin sdk.Coin) error {
> ```

nit: I would change Save -> Upsert since it is more SQL-like syntax 
___
*[`database/bank.go` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njro0hp89DoRrMptpJF:-Njro0hp89DoRrMptpJG:b-jw79ee) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/bank.go#L33)):*
> ```Go
> func (db *Db) SaveAccountDenomBalance(account string, coin sdk.Coin) error {
> 	query := `
> INSERT INTO account_denom_balance (account, denom, amount) 
> ```

have you checked if we don't have similar table where we store acc balances ?

Or when opening explorer we query full node each time ?
___
*[`database/schema/17-tokenholders.sql` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njro_orCX2rcWwGYsbW:-Njro_orCX2rcWwGYsbX:b-nfddb5) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/schema/17-tokenholders.sql#L3)):*
> ```TSQL
> CREATE TABLE account_denom_balance
> (
>     account         TEXT        NOT NULL,
> ```

I don't think that TEXT is the best option
Should be VARCHAR probably
same for amount
___
*[`database/schema/17-tokenholders.sql` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjrokAN9SEftfOs2TDm:-NjrokAN9SEftfOs2TDn:bbr1q9o) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/schema/17-tokenholders.sql#L6)):*
> ```TSQL
>     denom           TEXT        NOT NULL,
>     amount          TEXT        NOT NULL,
>     PRIMARY KEY(account, denom)
> ```

IDK if it is good option to use 2 strings as primary key or it is ok ?
I think I read some time ago that integer is the most optimized

Don't take it as granted
___
*[`database/types/account_balance.go` line 9 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjrnWKJArG1hoy3tPk_:-NjrnWKJArG1hoy3tPka:b-sk1riv) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/types/account_balance.go#L9)):*
> ```Go
> 	Account string `db:"account"`
> 	Denom   string `db:"denom"`
> 	Aalance string `db:"amount"`
> ```

should be balance
Also db tag is wrong
___
*[`database/types/account_balance.go` line 12 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjrnhWo7P1DuiBwDFo0:-NjrnhWo7P1DuiBwDFo1:bl9j4uq) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/types/account_balance.go#L12)):*
> ```Go
> }
> 
> // NewSupplyRow allows to easily create a new NewSupplyRow
> ```

outdated comment
check other places



_Code quote:_
```Go
NewSupplyRow all
```
___
*[`modules/bank/handle_msg.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njrq-Ap6InrAcxMFZZH:-Njrq-Aq8Aj2PJ5xMtRm:beloza2) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L66)):*
> ```Go
> 
> 		if quriedBalance.Amount.IsZero() {
> 			if err := m.db.DeleteAccountDenomBalance(account, *quriedBalance); err != nil {
> ```

if is not needed here

just `return m.db.DeleteAccountDenomBalance(account, *quriedBalance)`
___
*[`modules/bank/handle_msg.go` line 73 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njrq9e6DoVamZHJ599w:-Njrq9e6DoVamZHJ599x:bw0kxgr) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L73)):*
> ```Go
> 				return err
> 			}
> 		}
> ```

the whole thing could be simplified
```
if quriedBalance.Amount.IsZero() {
  return m.db.DeleteAccountDenomBalance(account, *quriedBalance)
}

return m.db.SaveAccountDenomBalance(account, *quriedBalance)

```
___
*[`modules/bank/source/local/source.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjrqUlN6pHDpyhsDM3U:-NjrqUlN6pHDpyhsDM3V:bo3c22a) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/source/local/source.go#L106)):*
> ```Go
> 		return nil, fmt.Errorf("error while loading height: %s", err)
> 	}
> 	balRes, err := s.q.Balance(sdk.WrapSDKContext(ctx), &banktypes.QueryBalanceRequest{Address: address, Denom: denom})
> ```

Do u know how this works ? 
Does it query node each time for each tx ?


<!-- Sent from Reviewable.io -->

2023-11-23 06:37 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: all files reviewed, 14 unresolved discussions (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`database/bank.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njup3iV7ge6MQp4ySw3:-Njup3iV7ge6MQp4ySw4:b-463j01) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/bank.go#L30)):*
> ```Go
> }
> 
> // SaveSupply allows to save for the given height the given total amount of coins
> ```

The comments here and in the folowwing method are invalid.
___
*[`database/bank.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjroK194Eg-dkyQbOPr:-Njunz4Z6o2sc_RExl3D:bd5x3b6) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/bank.go#L31)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: I would change Save -> Upsert since it is more SQL-like syntax
</blockquote></details>

`Save` is same as `Upsert`, both are valid names. 
___
*[`database/schema/17-tokenholders.sql` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njro_orCX2rcWwGYsbW:-NjuoOlE8wL06DNnyNpX:b17t690) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/schema/17-tokenholders.sql#L3)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't think that TEXT is the best option
Should be VARCHAR probably
same for amount
</blockquote></details>

The TEXT and VARCHAR is amost the same type.  And all table uses TEXT for address now.
___
*[`database/schema/17-tokenholders.sql` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjuoqBZ0bC844BtEvwA:-NjuoqBZ0bC844BtEvwB:b-6oouvb) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/schema/17-tokenholders.sql#L3)):*
> ```TSQL
> CREATE TABLE account_denom_balance
> (
>     account         TEXT        NOT NULL,
> ```

Let's rename to account_address or holder_address, to follow common style
___
*[`database/schema/17-tokenholders.sql` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjrokAN9SEftfOs2TDm:-NjuoE341b9sZS0jrBj5:bkkupdy) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/schema/17-tokenholders.sql#L6)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

IDK if it is good option to use 2 strings as primary key or it is ok ?
I think I read some time ago that integer is the most optimized

Don't take it as granted
</blockquote></details>

IMO the key is fully correct here.
___
*[`modules/bank/handle_msg.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjupmS30LqldOE7Eg9j:-NjupmS30LqldOE7Eg9k:b-hyyu0a) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L13)):*
> ```Go
> 
> // HandleMsg implements modules.MessageModule
> func (m *Module) HandleMsg(index int, msg sdk.Msg, tx *juno.Tx) error {
> ```

The message here might be provided from any block and in-prallel from multiple go-routines. And 100% of the messages will contain events you are looking for. So
1) You should filter the `ucore` amounts since all users have it, and 100% transactions in the events have it since the fee for any tx is paid in `ucore` (you can take the `ucore` from the config of the bdjuno, it is already loaded, check main file).
2) You should keep the `tx.Height` for each record and check if the currently stored hight is less than the height of the tx. If you won't follow this, you will DDOS the node with the requests you don't need. 
3) Since that method can be called in parallel you need to update your `Save` to `Save with where height < tx.Heigh`   (similar to optimistic locking). Since you can check in parallel that you need to write height 5 and 6, but 6 will written first and 5 will override it which is wrong. Same about the `Delete`. 
___
*[`modules/bank/handle_msg.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjusgGS--OJGpeJiVoi:-NjusgGS--OJGpeJiVoj:b-6i8k7l) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L30)):*
> ```Go
> 	}
> 
> 	return m.updateBalanceForEventType(index, tx, banktypes.EventTypeCoinSpent)
> ```

Probably it is better to pass multiple event typtes instead of 2 calls ?
___
*[`modules/bank/handle_msg.go` line 56 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njusyjj5N9dUhKNtX-Q:-Njusyjj5N9dUhKNtX-R:bpt5qo8) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L56)):*
> ```Go
> 		}
> 
> 		quriedBalance, err := m.keeper.GetAccountDenomBalance(account, coin.Denom)
> ```

IMO you shouldn't  call it for each event, you should collect all accounts you need with the denoms and call it once, since the accounts might be duplicated in events.


<!-- Sent from Reviewable.io -->

2023-11-24 11:41 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: all files reviewed, 14 unresolved discussions (waiting on @dzmitryhil, @keyleu, @wojtek-coreum, and @ysv)

___
*[`database/bank.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njup3iV7ge6MQp4ySw3:-Nk-JY-I-2JCgYTGVi_-:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/bank.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The comments here and in the folowwing method are invalid.
</blockquote></details>

Done.
___
*[`database/bank.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjroK194Eg-dkyQbOPr:-Nk-JZ3sEx7b7EKDOOa-:bmr9l7r) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/bank.go#L31)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

`Save` is same as `Upsert`, both are valid names.
</blockquote></details>

They use save for the exact same purpose. I think we should comply with the style used in the code base. 
___
*[`database/bank.go` line 33 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njro0hp89DoRrMptpJF:-Nk-JhsX2BwpDeOMVrg9:b-a0e0m5) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/bank.go#L33)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

have you checked if we don't have similar table where we store acc balances ?

Or when opening explorer we query full node each time ?
</blockquote></details>

I have checked. we don't have this. 
___
*[`database/schema/17-tokenholders.sql` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njro_orCX2rcWwGYsbW:-Nk-JmjO99vf0cKFsvTd:bukexjb) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/schema/17-tokenholders.sql#L3)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The TEXT and VARCHAR is amost the same type.  And all table uses TEXT for address now.
</blockquote></details>

TEXT is a better option than varchar in general, and it is the only string type used in this database, so we should comply with the style. 
___
*[`database/schema/17-tokenholders.sql` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjuoqBZ0bC844BtEvwA:-Nk-L5_D36oY7zaZRO4i:b-aslydv) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/schema/17-tokenholders.sql#L3)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Let's rename to account_address or holder_address, to follow common style
</blockquote></details>

to go with the same style, we should go with `address` 
___
*[`database/schema/17-tokenholders.sql` line 6 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjrokAN9SEftfOs2TDm:-Nk-LEzv-hK5zyXGs9wQ:b-v4ifgu) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/schema/17-tokenholders.sql#L6)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO the key is fully correct here.
</blockquote></details>

we will need with compound key anyways for queries and it is the uniqueness criteria, so introducing new integer type just as primary key is a waster of resources here. 
___
*[`database/types/account_balance.go` line 9 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjrnWKJArG1hoy3tPk_:-Nk-L_1OB-BeQPzCxWPe:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/types/account_balance.go#L9)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

should be balance
Also db tag is wrong
</blockquote></details>

Done.
___
*[`database/types/account_balance.go` line 12 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjrnhWo7P1DuiBwDFo0:-Nk-M28z6WY5gCf-rjQF:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/types/account_balance.go#L12)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

outdated comment
check other places
</blockquote></details>

Done.
___
*[`modules/bank/handle_msg.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjupmS30LqldOE7Eg9j:-Nk-Rr-6D5n9MYZD3Fn2:bj59gbw) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The message here might be provided from any block and in-prallel from multiple go-routines. And 100% of the messages will contain events you are looking for. So
1) You should filter the `ucore` amounts since all users have it, and 100% transactions in the events have it since the fee for any tx is paid in `ucore` (you can take the `ucore` from the config of the bdjuno, it is already loaded, check main file).
2) You should keep the `tx.Height` for each record and check if the currently stored hight is less than the height of the tx. If you won't follow this, you will DDOS the node with the requests you don't need. 
3) Since that method can be called in parallel you need to update your `Save` to `Save with where height < tx.Heigh`   (similar to optimistic locking). Since you can check in parallel that you need to write height 5 and 6, but 6 will written first and 5 will override it which is wrong. Same about the `Delete`.
</blockquote></details>

if we filter ucore, we will need another strategy to get the ucore holders, since right now it is the only token which will go to UI. 
2 and 3 done.
___
*[`modules/bank/handle_msg.go` line 30 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjusgGS--OJGpeJiVoi:-Nk-MTcTDDohVWEzC1MM:b-d3e5n5) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L30)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Probably it is better to pass multiple event typtes instead of 2 calls ?
</blockquote></details>

it will be 2 calls underneath that one call anyways.
___
*[`modules/bank/handle_msg.go` line 56 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njusyjj5N9dUhKNtX-Q:-Nk-NMiw9W41wI-IArGN:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L56)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

IMO you shouldn't  call it for each event, you should collect all accounts you need with the denoms and call it once, since the accounts might be duplicated in events.
</blockquote></details>

Done.
___
*[`modules/bank/handle_msg.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njrq-Ap6InrAcxMFZZH:-Nk-MvOE8NHi1PnXPili:b-4hro7n) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L66)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

if is not needed here

just `return m.db.DeleteAccountDenomBalance(account, *quriedBalance)`
</blockquote></details>

this is a for loop, we don't want to return unless there is an error.
___
*[`modules/bank/handle_msg.go` line 73 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njrq9e6DoVamZHJ599w:-Nk-N000714RqBNGlKeL:b-xww24e) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/ha [...]

2023-11-27 09:04 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: 2 of 11 files reviewed, 12 unresolved discussions (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`database/bank.go` line 55 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-Jm_-lHG-MzXObCC:-NkF-Jm_-lHG-MzXObCD:bxc0tdo) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/database/bank.go#L55)):*
> ```Go
> ON CONFLICT (address,denom) DO UPDATE 
>     SET amount=$3, height=$4
> WHERE account_denom_balance.address=$1 AND account_denom_balance.denom=$2`
> ```

The `Sql` is not thread safe you need to use height here as well.
___
*[`database/bank.go` line 66 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkEzmMh40vZtbbCwcwp:-NkEzmMh40vZtbbCwcwq:b-uxzqf2) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/database/bank.go#L66)):*
> ```Go
> 
> // DeleteAccountDenomBalance allows to delete the balance of an account for a given denom.
> func (db *Db) DeleteAccountDenomBalance(account string, coin sdk.Coin) error {
> ```

I would improve the logic by the removing of the `Delete` method, since it is currently not thread safe and since you are anyways building the VIEW better to use `Save` only and in the `selecte * where balance > 0`. That will simplify your code. 
___
*[`modules/bank/handle_msg.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjupmS30LqldOE7Eg9j:-NkF-XA_EM05KOjBDBN9:b-sz5crc) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L13)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

if we filter ucore, we will need another strategy to get the ucore holders, since right now it is the only token which will go to UI. 
2 and 3 done.
</blockquote></details>

Discussed with team, decided to skip `core`.
___
*[`modules/bank/handle_msg.go` line 71 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-yup32BnMTKXwfuT:-NkF-yup32BnMTKXwfuU:bsb761m) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/modules/bank/handle_msg.go#L71)):*
> ```Go
> 	for ad := range addressDenomMap {
> 		storedBalance, found, err := m.db.GetAccountDenomBalance(ad.address, ad.denom)
> 		if found && storedBalance.Height >= block.Height {
> ```

Not sure that the logic is correct, since you compare different tables height. So you should either query the same table, or don't you that check at all, since you have `where newHeight >= oldHeigh`  rule in the insert.


<!-- Sent from Reviewable.io -->

2023-11-27 15:42 UTC, ysv requested changes
> Reviewed 8 of 9 files at r2, 1 of 1 files at r3, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`database/bank.go` line 31 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjroK194Eg-dkyQbOPr:-NkGOFuQ1r_A9tUP8g1O:b-o2eumt) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/bank.go#L31)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

They use save for the exact same purpose. I think we should comply with the style used in the code base.
</blockquote></details>

sure, I'm ok just a nit
___
*[`database/bank.go` line 55 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-Jm_-lHG-MzXObCC:-NkGOSU2-D8lM0fJBVcZ:b-j2m6xz) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/database/bank.go#L55)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

The `Sql` is not thread safe you need to use height here as well.
</blockquote></details>

By the way that is very reasonable comment
How will this work if we do rescanning by bdjuno ?
___
*[`database/bank.go` line 66 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkEzmMh40vZtbbCwcwp:-NkGO_tyEEedFzyRWX60:b-gsthcv) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/database/bank.go#L66)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I would improve the logic by the removing of the `Delete` method, since it is currently not thread safe and since you are anyways building the VIEW better to use `Save` only and in the `selecte * where balance > 0`. That will simplify your code.
</blockquote></details>

Makes sense for me
___
*[`database/schema/17-tokenholders.sql` line 3 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njro_orCX2rcWwGYsbW:-NkGOgFH3qxCT5fRolOi:bl6tluv) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/database/schema/17-tokenholders.sql#L3)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

TEXT is a better option than varchar in general, and it is the only string type used in this database, so we should comply with the style.
</blockquote></details>

style - OK
___
*[`modules/bank/handle_msg.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njrq-Ap6InrAcxMFZZH:-NkGPLAe-xjymfpYH4ja:bfsgilk) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L66)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

this is a for loop, we don't want to return unless there is an error.
</blockquote></details>

didn't mention the loop
___
*[`modules/bank/handle_msg.go` line 71 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-yup32BnMTKXwfuT:-NkGQWffBnfgvVL8UoM6:b-emp05z) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/modules/bank/handle_msg.go#L71)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Not sure that the logic is correct, since you compare different tables height. So you should either query the same table, or don't you that check at all, since you have `where newHeight >= oldHeigh`  rule in the insert.
</blockquote></details>

I don't like this approach either but I have another idea.
We can write smarter sql statement so it doesn't override balance if heigh is outdated

base idea:

```
INSERT INTO your_table (id, balance, height)
VALUES (1, new_balance_value, new_height_value)
ON CONFLICT (id)
DO UPDATE SET
  balance = CASE WHEN excluded.height > your_table.height THEN excluded.balance ELSE your_table.balance END,
  height = CASE WHEN excluded.height > your_table.height THEN excluded.height ELSE your_table.height END;
```
___
*[`modules/bank/source/local/source.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjrqUlN6pHDpyhsDM3U:-NkGPUsuCO1grD2BR7yN:bok2sc1) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/source/local/source.go#L106)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

yes, it queries the node every time.
</blockquote></details>

but is it ok to do it like this ? Do they also do such queries in other modules ?


<!-- Sent from Reviewable.io -->

2023-11-28 05:04 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: all files reviewed, 5 unresolved discussions (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/bank/handle_msg.go` line 71 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-yup32BnMTKXwfuT:-NkJIZZP01qQOt70QpQ-:bploxr0) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/modules/bank/handle_msg.go#L71)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

I don't like this approach either but I have another idea.
We can write smarter sql statement so it doesn't override balance if heigh is outdated

base idea:

```
INSERT INTO your_table (id, balance, height)
VALUES (1, new_balance_value, new_height_value)
ON CONFLICT (id)
DO UPDATE SET
  balance = CASE WHEN excluded.height > your_table.height THEN excluded.balance ELSE your_table.balance END,
  height = CASE WHEN excluded.height > your_table.height THEN excluded.height ELSE your_table.height END;
```
</blockquote></details>

Actually, you can archive the same if you only check the height in the `WHERE`, but with the simpler sintax.


<!-- Sent from Reviewable.io -->

2023-11-28 08:20 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @keyleu, @wojtek-coreum, and @ysv)

___
*[`database/bank.go` line 55 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-Jm_-lHG-MzXObCC:-NkJmTIA9rEVQsmWuStK:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/database/bank.go#L55)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

By the way that is very reasonable comment
How will this work if we do rescanning by bdjuno ?
</blockquote></details>

Done.
___
*[`database/bank.go` line 66 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkEzmMh40vZtbbCwcwp:-NkJmVeT38a9SRo_QKq7:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/database/bank.go#L66)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Makes sense for me
</blockquote></details>

Done.
___
*[`modules/bank/handle_msg.go` line 13 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjupmS30LqldOE7Eg9j:-NkK-Wdl7rkwMw6KShoF:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L13)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Discussed with team, decided to skip `core`.
</blockquote></details>

Done.
___
*[`modules/bank/handle_msg.go` line 66 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-Njrq-Ap6InrAcxMFZZH:-NkJm0iY6KXu0M9aF80B:bvu2q2f) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/handle_msg.go#L66)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

didn't mention the loop
</blockquote></details>

the logic is now change that we have removed the Delete function. 
___
*[`modules/bank/handle_msg.go` line 71 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-yup32BnMTKXwfuT:-NkJlb7YEwHqUSqirJXo:blg2219) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/modules/bank/handle_msg.go#L71)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Actually, you can archive the same if you only check the height in the `WHERE`, but with the simpler sintax.
</blockquote></details>

The reason for this check is to avoid unnecessary queires to the node, not to avoid race condition, the race condition will be resolved by sql query.
___
*[`modules/bank/source/local/source.go` line 106 at r1](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NjrqUlN6pHDpyhsDM3U:-NkJmDXfAku-29fikhjb:bh9ruql) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/1c753efd17d89368235fdf7f93b6c15f10c09b85/modules/bank/source/local/source.go#L106)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

but is it ok to do it like this ? Do they also do such queries in other modules ?
</blockquote></details>

yes, that is how they do it. 


<!-- Sent from Reviewable.io -->

2023-11-28 09:14 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: 7 of 14 files reviewed, 7 unresolved discussions (waiting on @keyleu, @miladz68, @wojtek-coreum, and @ysv)

___
*[`modules/bank/handle_msg.go` line 71 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-yup32BnMTKXwfuT:-NkKAgYA7yZu52UDqLle:b-30rf2z) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/modules/bank/handle_msg.go#L71)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

The reason for this check is to avoid unnecessary queires to the node, not to avoid race condition, the race condition will be resolved by sql query.
</blockquote></details>

But see, you allways query at least once, and additionally save, in case you need it. 
If you save-only the number of the requests to the DB will be even less. 
___
*[`modules/bank/module.go` line 26 at r4](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKByQm7-WZ3A7zb2E2:-NkKByQm7-WZ3A7zb2E3:b-ksir2m) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/5b961b04fb4e6383fcb75a2f9f234453de5cdbee/modules/bank/module.go#L26)):*
> ```Go
> 	messageParser junomessages.MessageAddressesParser
> 	keeper        source.Source
> 	govDenom      string
> ```

probably `baseDenom` same for the method name.
___
*[`modules/bank/module.go` line 51 at r4](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKBBYM2Z63hJ1FKxyz:-NkKBBYM2Z63hJ1FKxz-:b-jbs3pv) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/5b961b04fb4e6383fcb75a2f9f234453de5cdbee/modules/bank/module.go#L51)):*
> ```Go
> }
> 
> func getGovTokenFromAddressPrefix(addressPrefix string) string {
> ```

Use the coreum constants please, we already defined those values. 


<!-- Sent from Reviewable.io -->

2023-11-28 09:41 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: 7 of 14 files reviewed, 7 unresolved discussions (waiting on @dzmitryhil, @keyleu, @wojtek-coreum, and @ysv)

___
*[`modules/bank/handle_msg.go` line 71 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-yup32BnMTKXwfuT:-NkKGA6F2EkVHjntmadt:b-w1bkya) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/modules/bank/handle_msg.go#L71)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

But see, you allways query at least once, and additionally save, in case you need it. 
If you save-only the number of the requests to the DB will be even less.
</blockquote></details>

DB can handle way more queries than the node (orders of magnitude more) so saving on node load is worth it IMO. 
___
*[`modules/bank/module.go` line 26 at r4](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKByQm7-WZ3A7zb2E2:-NkKHuC98nHvqn2wZbCb:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/5b961b04fb4e6383fcb75a2f9f234453de5cdbee/modules/bank/module.go#L26)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

probably `baseDenom` same for the method name.
</blockquote></details>

Done.
___
*[`modules/bank/module.go` line 51 at r4](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKBBYM2Z63hJ1FKxyz:-NkKHtN148qvIlsbdCXp:b-896fix) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/5b961b04fb4e6383fcb75a2f9f234453de5cdbee/modules/bank/module.go#L51)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

Use the coreum constants please, we already defined those values.
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2023-11-28 10:35 UTC, dzmitryhil requested changes
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: 7 of 14 files reviewed, 3 unresolved discussions (waiting on @keyleu, @wojtek-coreum, and @ysv)

___
*[`modules/bank/handle_msg.go` line 71 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-yup32BnMTKXwfuT:-NkKUkR18hlHJnh5QA5X:b-yhrd2o) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/modules/bank/handle_msg.go#L71)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

DB can handle way more queries than the node (orders of magnitude more) so saving on node load is worth it IMO.
</blockquote></details>

I see, right. But is it ok that you compare the block.Height from block table with the block.Height  from account_balance table?


<!-- Sent from Reviewable.io -->

2023-11-28 11:02 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: 7 of 14 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @keyleu, @wojtek-coreum, and @ysv)

___
*[`modules/bank/handle_msg.go` line 71 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-yup32BnMTKXwfuT:-NkK_x0P6e0Mhy36z1De:b5g0fom) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/modules/bank/handle_msg.go#L71)):*
<details><summary><i>Previously, dzmitryhil (Dzmitry Hil) wrote…</i></summary><blockquote>

I see, right. But is it ok that you compare the block.Height from block table with the block.Height  from account_balance table?
</blockquote></details>

i think yes, that is how it is done in all other modules, I assume that block height is written to database and only then, the messages are processed. 


<!-- Sent from Reviewable.io -->

2023-11-28 11:07 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: 7 of 14 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @keyleu, @wojtek-coreum, and @ysv)

___
*[`modules/bank/handle_msg.go` line 71 at r3](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkF-yup32BnMTKXwfuT:-NkKaFZz1yh9oSGxgFXb:bcvpgr9) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/29b23c75bfb75c2262106206053e9178d4868f4d/modules/bank/handle_msg.go#L71)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

i think yes, that is how it is done in all other modules, I assume that block height is written to database and only then, the messages are processed.
</blockquote></details>

My previous answer is not very accurate, I compare the latest processed block height with the latest processed transaction height, given any race condition, the latest block is guaranteed to be processed, so it should be fine. 


<!-- Sent from Reviewable.io -->

2023-11-28 11:37 UTC, ysv requested changes
> Reviewed 5 of 7 files at r4, 2 of 2 files at r5, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: all files reviewed, 5 unresolved discussions (waiting on @dzmitryhil, @keyleu, @miladz68, and @wojtek-coreum)

___
*[`database/schema/17-tokenholders.sql` line 13 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKgmOD6ECfneNrnLtj:-NkKgmOD6ECfneNrnLtk:b-kl17q3) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/database/schema/17-tokenholders.sql#L13)):*
> ```TSQL
>     SELECT denom, COUNT(*) AS holders
>     FROM account_denom_balance
>     where amount != '0'
> ```

nit: lets use uppercase as everywhere
___
*[`modules/bank/handle_msg.go` line 66 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKi61eDgh6e0aII7By:-NkKi61eDgh6e0aII7Bz:b-7t0c9v) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/modules/bank/handle_msg.go#L66)):*
> ```Go
> 		}
> 
> 		if coin.Denom == m.baseDenom {
> ```

nit: pls add comment
___
*[`modules/bank/module.go` line 54 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKhbZE0x-37ct9-uAJ:-NkKhbZE0x-37ct9-uAK:b7l1z1x) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/modules/bank/module.go#L54)):*
> ```Go
> 
> func getBaseTokenFromAddressPrefix(addressPrefix string) string {
> 	switch addressPrefix {
> ```

nit: using map here might look a bit better

```
mapp[string]string{
  constant.AddressPrefixMain: constant.DenomMain,
}[addressPrefix]
...
```
___
*[`modules/bank/module.go` line 62 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKhpaDA5LfdhZa3rds:-NkKhpaDA5LfdhZa3rdt:b-bov7c6) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/modules/bank/module.go#L62)):*
> ```Go
> 		return constant.DenomDev
> 	default:
> 		return ""
> ```

do you think it is ok to return "" empty string here ?
Maybe we should return error ?


<!-- Sent from Reviewable.io -->

2023-11-28 11:45 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: 12 of 14 files reviewed, 3 unresolved discussions (waiting on @dzmitryhil, @keyleu, @wojtek-coreum, and @ysv)

___
*[`database/schema/17-tokenholders.sql` line 13 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKgmOD6ECfneNrnLtj:-NkKj6Mr5_eUT91uYyKA:b-of3om0) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/database/schema/17-tokenholders.sql#L13)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: lets use uppercase as everywhere
</blockquote></details>

Done. good point.
___
*[`modules/bank/handle_msg.go` line 66 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKi61eDgh6e0aII7By:-NkKj7oq6M7ZqrJ3Iluk:bb6un1j) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/modules/bank/handle_msg.go#L66)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: pls add comment
</blockquote></details>

Done
___
*[`modules/bank/module.go` line 54 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKhbZE0x-37ct9-uAJ:-NkKikcODvSXyNhBAXgq:bmm48x5) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/modules/bank/module.go#L54)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

nit: using map here might look a bit better

```
mapp[string]string{
  constant.AddressPrefixMain: constant.DenomMain,
}[addressPrefix]
...
```
</blockquote></details>

doing a map for only 3 conditions seems too much, it is less readable and less performant. 
___
*[`modules/bank/module.go` line 62 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKhpaDA5LfdhZa3rds:-NkKiZIt53PmGoRHPSSc:bnnq4n4) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/modules/bank/module.go#L62)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

do you think it is ok to return "" empty string here ?
Maybe we should return error ?
</blockquote></details>

I think empty string is fine, since it is only for optimization purpose. we can return an error though, but not returning and error works ok as well. 


<!-- Sent from Reviewable.io -->

2023-11-28 13:25 UTC, dzmitryhil submitted a review, later dismissed
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-:-NkL5l4I7U-P-coo6fvP:bnfp4nl)* status: 12 of 14 files reviewed, 2 unresolved discussions (waiting on @keyleu, @wojtek-coreum, and @ysv)



<!-- Sent from Reviewable.io -->

2023-11-28 15:55 UTC, ysv requested changes
> Reviewed 2 of 2 files at r6, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @miladz68, and @wojtek-coreum)

___
*[`modules/bank/module.go` line 54 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKhbZE0x-37ct9-uAJ:-NkLcdyU8pV5QhP-vxeM:bucpw2i) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/modules/bank/module.go#L54)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

doing a map for only 3 conditions seems too much, it is less readable and less performant.
</blockquote></details>

IMO more readable but ok
___
*[`modules/bank/module.go` line 62 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKhpaDA5LfdhZa3rds:-NkLchAj8NshEHFGAgkK:b-dvi7ve) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/modules/bank/module.go#L62)):*
<details><summary><i>Previously, miladz68 (milad) wrote…</i></summary><blockquote>

I think empty string is fine, since it is only for optimization purpose. we can return an error though, but not returning and error works ok as well.
</blockquote></details>

Hm, but if we receive some denom prefix which is not expected it means that we have added new network or smth like this. And probably denom is different also, which means that we better error to detect mistake right away rather then find it later


<!-- Sent from Reviewable.io -->

2023-11-29 11:09 UTC, miladz68 reviewed
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: all files reviewed, 1 unresolved discussion (waiting on @keyleu, @wojtek-coreum, and @ysv)

___
*[`modules/bank/module.go` line 62 at r5](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40#-NkKhpaDA5LfdhZa3rds:-NkPk2NfEz_xF5LJlv1f:b-kfrun8) ([raw file](https://github.com/CoreumFoundation/bdjuno/blob/f2fa91c3727dcf1eb3b1eccf3710c407ed21e61f/modules/bank/module.go#L62)):*
<details><summary><i>Previously, ysv (Yaroslav Savchuk) wrote…</i></summary><blockquote>

Hm, but if we receive some denom prefix which is not expected it means that we have added new network or smth like this. And probably denom is different also, which means that we better error to detect mistake right away rather then find it later
</blockquote></details>

Good point, I will add panic as the default branch. we have to panic since error handling is not part of the `registrar` interface. 


<!-- Sent from Reviewable.io -->

2023-11-29 11:55 UTC, ysv approved these changes
> Reviewed 2 of 2 files at r7, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/CoreumFoundation/bdjuno/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @keyleu and @wojtek-coreum)



<!-- Sent from Reviewable.io -->

2023-11-29 12:00 UTC, merged